<?php 

	$ASSIGNMENTS_TABLE = "timesheet_assignments";
	$CLIENT_TABLE = "timesheet_client";
	$CONFIG_TABLE = "timesheet_configuration";
	$PROJECT_TABLE = "timesheet_project";
	$TASK_TABLE = "timesheet_task";
	$TASK_ASSIGNMENTS_TABLE = "timesheet_task_assignments";
	$TIMES_TABLE = "timesheet_times";
	$USER_TABLE = "timesheet_user";
	$RATE_TABLE = "timesheet_billrate";
	$ABSENCE_TABLE = "timesheet_absences";
	$ALLOWANCE_TABLE = "timesheet_allowances";

?>